# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-28 16:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('village', models.CharField(max_length=30)),
                ('mobile', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('is_sale_product', models.BooleanField(default=False)),
                ('notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductBuyingDestination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('latitude', models.CharField(blank=True, max_length=40, null=True)),
                ('longitude', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_quantity', models.IntegerField()),
                ('purchase_date', models.DateField()),
                ('available_quantity', models.IntegerField()),
                ('expiry_date', models.DateField()),
                ('is_over', models.FloatField(default=False)),
                ('date_over', models.DateField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile.Product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ServiceIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile.Product')),
                ('product_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile.ProductUnit')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_admit', models.DateTimeField()),
                ('is_dispatched', models.BooleanField(default=False)),
                ('date_dispatched', models.DateTimeField(blank=True, null=True)),
                ('service_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('received_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('is_transaction_over', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRecivedCostStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ServiceStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('product_buying_destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile.ProductBuyingDestination')),
            ],
        ),
        migrations.CreateModel(
            name='TripBuyingExpense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile.Trip')),
            ],
        ),
        migrations.CreateModel(
            name='TripExpenseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('notes', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='tripbuyingexpense',
            name='trip_expense_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile.TripExpenseType'),
        ),
        migrations.AddField(
            model_name='serviceinventory',
            name='received_cost_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile.ServiceRecivedCostStatus'),
        ),
        migrations.AddField(
            model_name='serviceinventory',
            name='service_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile.ServiceProduct'),
        ),
        migrations.AddField(
            model_name='serviceinventory',
            name='service_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile.ServiceStatus'),
        ),
        migrations.AddField(
            model_name='serviceingredient',
            name='service_inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile.ServiceInventory'),
        ),
        migrations.AddField(
            model_name='productinventory',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile.Trip'),
        ),
        migrations.AddField(
            model_name='productinventory',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile.ProductUnit'),
        ),
    ]
